steps:
  - name: gcr.io/cloud-builders/docker
    dir: backend
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/notes-backend
      - .

  - name: gcr.io/cloud-builders/docker
    dir: backend
    args:
      - push
      - gcr.io/$PROJECT_ID/notes-backend

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    dir: backend
    entrypoint: gcloud
    args:
      - run
      - deploy
      - notes-backend
      - --image
      - gcr.io/$PROJECT_ID/notes-backend
      - --region
      - asia-southeast2
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/notes-backend
